### PR TITLE
Globe creation

### PR DESCRIPTION
**Pull request by markgregory757**
Added a globe to the page

### CODE REVIEW

**Comment by markgregory757** [comment]
This push has a lot of errors I can't solve yet.

**Comment by thomasmama14** [comment]
I am looking over this now. I just want to read through some of the conflicts and be sure it's ready to merge.

**Comment by thomasmama14** [comment]
What kind of errors are you concerned about in it?

**Comment by thomasmama14** [comment]
My understanding is we should only push to main when it is working without errors. Would recommend not pushing until errors are resolved. 

There is a lot in this push and I want to verify what errors are involved before pushing to main.

**Pull request closed without merging**
